book/urls.py
from book import views
from django.urls import path

urlpatterns=[
    path('', views.index, name="index_book"),
    path('create/', views.create_book, name="create_book"),
    path('update/<int:book_id>', views.update_book, name="update_book"),
    path('delete/<int:book_id>', views.delete_book, name="delete_book"),
]

combine/urls.py
from combine import views
from django.urls import path
 
app_name = 'combine'
 
urlpatterns=[
    path('', views.HomePageView.as_view(), name='home'),
    path('getnum/',views.Api.getNums, name='get-num'),
    path('getavg/',views.Api.getAvg, name='get-avg'),
    path('getgraph/',views.Api.getGraph, name='get-graph'),
    path('getdata/',views.Api.getData, name='get-data'),
    path('get-seaborn-graph/',views.Api.getSeabornGraph, name='get-seaborn-graph'),
    path('chart/',views.HomeView.as_view(), name='home-view'),
    path('chart-api/',views.ChartData.as_view(), name='chart-api'),
    path('plotly-chart/',views.PlotlyChartView.as_view(), name='plotly-chart'),
    path('book-table/',views.BookTableView.as_view(), name='book-table'),
    path('user-table/',views.UserTableView.as_view(), name='user-table')
]

forward/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from forward.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_DIR, MEDIA_ROOT, MEDIA_URL
from hello_world import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^hello_world/', include('hello_world.urls')),
    re_path(r'^combine/', include('combine.urls')),
    re_path(r'^book/', include('book.urls')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

hello_world/urls.py
from django.urls import re_path
from hello_world import views

app_name = "hello_world"

urlpatterns=[
    re_path(r'^register/$', views.register, name="register"),
    re_path(r'^user_login/$', views.user_login, name="user_login"),
]

hello_world/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    # A one-to-one relationship. Conceptually, this is similar to a ForeignKey with unique=True, 
    # but the "reverse" side of the relation will directly return a single object.

    # ON DELETE CASCADE constraint is used in MySQL to delete the rows from the child table automatically, 
    # when the rows from the parent table are deleted.

    occupation = models.TextField(blank=True)
    company = models.TextField(blank=True)
    hobby = models.TextField(blank=True)

    def __str__(self):
        return self.user.username

hello_world/forms.py
from django import forms 
from hello_world.models import UserProfileInfo
from django.contrib.auth.models import User
 
class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta(): #the inner class of your model class.
        model = User
        fields = ('username','password','email')
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control','placeholder': 'Enter your username'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),
        }
 
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('occupation','company','hobby')
        widgets = {
            'occupation':forms.Textarea(attrs={'class':'form-control'}),
            'company':forms.Textarea(attrs={'class':'form-control'}),
            'hobby':forms.Textarea(attrs={'class':'form-control'}),
        }

hello_world/views.py
from django.shortcuts import render
from hello_world.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from hello_world.models import UserProfileInfo
 
# Create your views here.
def index(request):
    return render(request,'hello_world/index.html')
 
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
 
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False) #commit=False store in memory first instead of store in database 
            # memory storing (occupation... ) temporarily save is because we need to capture user id
            profile.user=user # capture user id
            profile.save() # save profile
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else: # if GET request
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
 
    return render(request,'hello_world/registration.html',
    {'user_form':user_form,
    'profile_form':profile_form,
    'registered':registered}
    )
 
def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request,'hello_world/login.html')

templates/hello_world/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Forward School Demo</title>
            <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
        </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    {# Django Home link | Admin Link | Register Link | Login | Logout #}
                    <li><a class="navbar-brand" href="{% url 'index' %}">Forward School</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'hello_world:register' %}">Register</a></li>
                    <li><a class="navbar-link" href="{% url 'index_book' %}">Book</a></li>
                    <li><a class="navbar-link" href="{% url 'combine:home' %}">Combine</a></li>

                    {# Add some logic if user is logged in or logged out #}
                    {% if user.is_authenticated %}
                        <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'hello_world:user_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

templates/hello_world/index.html
{% extends "hello_world/base.html" %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Welcome to Forward School</h1>
        {% if user.is_authenticated %}
            <h2>Hello {{user.username}}</h2>
        {% else %}
            <h2>Register or Login if you would like to</h2>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/hello_world/login.html
{% extends "hello_world/base.html" %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Login here:</h1>
        <form method="POST" action="{% url 'hello_world:user_login' %}">
            {% csrf_token %}
            {# This is the form to capture user data #}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username">

            <label for="username">Password:</label>
            <input type="password" name="password" placeholder="Password">

            <input type="submit" name="" value="Login">
        </form>
    </div>
</div>

{% endblock %}

templates/hello_world/registration.html
{% extends "hello_world/base.html" %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register here</h1>
            <h3>Just fill up the form</h3>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
    </div>
</div>

{% endblock %}