book/urls.py
from book import views
from django.urls import path

urlpatterns=[
    path('', views.index, name="index_book"),
    path('create/', views.create_book, name="create_book"),
    path('update/<int:book_id>', views.update_book, name="update_book"),
    path('delete/<int:book_id>', views.delete_book, name="delete_book"),
]

combine/urls.py
from combine import views
from django.urls import path
 
app_name = 'combine'
 
urlpatterns=[
    path('', views.HomePageView.as_view(), name='home'),
    path('getnum/',views.Api.getNums, name='get-num'),
    path('getavg/',views.Api.getAvg, name='get-avg'),
    path('getgraph/',views.Api.getGraph, name='get-graph'),
    path('getdata/',views.Api.getData, name='get-data'),
    path('get-seaborn-graph/',views.Api.getSeabornGraph, name='get-seaborn-graph'),
    path('chart/',views.HomeView.as_view(), name='home-view'),
    path('chart-api/',views.ChartData.as_view(), name='chart-api'),
    path('plotly-chart/',views.PlotlyChartView.as_view(), name='plotly-chart'),
    path('book-table/',views.BookTableView.as_view(), name='book-table'),
    path('user-table/',views.UserTableView.as_view(), name='user-table')
]

forward/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from forward.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_DIR, MEDIA_ROOT, MEDIA_URL
from hello_world import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^hello_world/', include('hello_world.urls')),
    re_path(r'^combine/', include('combine.urls')),
    re_path(r'^book/', include('book.urls')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

combine/models.py
from django.db import models

# Create your models here.

combine/views.py
from django.shortcuts import render
from django.http import HttpResponse
from forward.settings import MEDIA_ROOT
from django.views.generic import TemplateView
 
# Create your views here.
 
import numpy as np
import pandas as pd
import matplotlib as pl
pl.use('Agg') #Agg is a non-interactive backend, only save to files
import matplotlib.pyplot as plt
import seaborn as sb
 
class HomePageView(TemplateView):
    def get(self,request,**kwargs):
        return render(request, 'combine/index.html', context=None)
 
class Api(TemplateView):
    # Create your views here.
    def getNums(request):
        n = np.array([2,3,4])
        name1 = "name-1" + str(n[1])
        return HttpResponse('{"name":'+name1+',"age":31,"city":"New York"}')
 
    def getAvg(request):
        s1=request.GET.get("val","")
        print (s1)
        if len(s1)==0:
            return HttpResponse("none")
        l1=s1.split(',')
        ar=np.array(l1,dtype=int)
 
        return HttpResponse(str(np.average(ar)))
 
    def getGraph(request):
        x = np.arange(0,2 * np.pi, 0.01) # starts from 0, ends till 6.28 and adds by 0.01
        s = np.cos(x)**2 # ** is the operator for "power of".
        plt.plot(x,s)
 
        plt.xlabel('xlabel(X)')
        plt.ylabel('ylabel(y)')
        plt.title('Basic Graph!')
        plt.grid(True)
 
        response = HttpResponse(content_type="image/jpeg")
        plt.savefig(response, format="png")
        return response
 
    def getData(request):
        samp = np.random.randint(100,600,size=(4,5)) #size means the array size
        df = pd.DataFrame(samp, index=['alex','danny','lina','david'],columns=['Jan','Feb','Mar','Apr','May'])
        return HttpResponse(df.to_html(index=True, classes='table table-bordered'))
 
    def getSeabornGraph(request):
        file_path = MEDIA_ROOT+"/titanic_train.csv"
        df = pd.read_csv(file_path)
        graph = sb.factorplot(x='Survived',hue='Sex',data=df, col='Pclass',kind='count') #passenger class
        
        response = HttpResponse(content_type="image/jpeg")
        graph.savefig(response, format="png")
        return response
 
# Chapter 4: CHART.JS (Involves Javascript)
 
from rest_framework.views import APIView #Using the APIView class is pretty much the same as using a regular View class
from rest_framework.response import Response
 
class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'combine/charts.html')
 
class ChartData(APIView):
 
    def get(self, request, format=None):
        labels=['January','February',"March","April","May","June","July"]
        chartLabel="My Data"
        chartData=[0,10,5,2,20,30,45]
        data = {
            "labels":labels,
            "chartLabel":chartLabel, 
            "chartdata":chartData, 
        }
        return Response(data)
 
 
# Chapter 5: Plot.ly (Involves Javascript)
from plotly.offline import plot
import plotly.graph_objs as go
 
class PlotlyChartView(TemplateView):
    def get(self, request, *args, **kwargs):
        x_data=[0,1,2,3]
        y_data=[x**2 for x in x_data]
        plot_div = plot([go.Scatter(
            x=x_data,
            y=y_data,
            mode='lines',
            name='My Plotly Chart',
            opacity=0.8,
            marker_color='green'
        )], output_type='div')
 
        return render(request, 'combine/plotly.html', context={'plot_div':plot_div})
 
# Part 6: DJANGO-TABLES (Does not involves Javascript) #An app for creating HTML tables
import django_tables2 as tables
from book.models import Book
from hello_world.models import User, UserProfileInfo
 
# Table Class
class BookTable(tables.Table):
    class Meta:
        model = Book
 
# View
class BookTableView(tables.SingleTableView):
    table_class=BookTable
    queryset=Book.objects.all()
    template_name="combine/table.html"
 
# Table Class
class UserTable(tables.Table):
    class Meta:
        model = UserProfileInfo
 
# View
class UserTableView(tables.SingleTableView):
    table_class=UserTable
    queryset=UserProfileInfo.objects.all() #ORM Object Relation Mapping
    template_name="combine/table.html"

templates/combine/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link | Admin Link#}
          <li><a class="navbar-brand" href="{% url 'combine:home' %}">Forward School</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li> 
          <li><a class="navbar-link" href="{% url 'combine:home-view' %}">Chart</a></li>
          <li><a class="navbar-link" href="{% url 'combine:plotly-chart' %}">Plotly Chart</a></li>
          <li><a class="navbar-link" href="{% url 'combine:book-table' %}">Book Tables</a></li>
          <li><a class="navbar-link" href="{% url 'combine:user-table' %}">User Tables</a></li>
        </ul>
      </div>
    </nav>
    <div>
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/combine/charts.html
{% extends "combine/base.html" %}
{% block body_block %}
<div class="container-fluid">
    <center class="row">
        <h2>Our Implementation of <b>Chart.js</b> in Django</h2>
    </center>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <canvas id="myChartLine"></canvas>
        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <canvas id="myChartBar"></canvas>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
 <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script> 
<script>
    // Make API calls
    $.ajax({
        method: "GET",
        url: "{% url 'combine:chart-api' %}",
        success: function(data){
            drawLineGraph(data,'myChartLine');
            drawBarGraph(data,'myChartBar');
        },
        error: function(err){
            console.log(err);
        }
    })
 
    function drawLineGraph(data, id) { 
      var labels = data.labels; 
      var chartLabel = data.chartLabel; 
      var chartdata = data.chartdata; 
      var ctx = document.getElementById(id).getContext('2d'); 
      var chart = new Chart(ctx, { 
        // The type of chart we want to create 
        type: 'line', 
 
        // The data for our dataset 
        data: { 
          labels: labels, 
          datasets: [{ 
            label: chartLabel, 
            backgroundColor: 'rgb(255, 100, 200)', 
            borderColor: 'rgb(55, 99, 132)', 
            data: chartdata, 
          }] 
        }, 
 
        // Configuration options go here 
        options: { 
          scales: { 
            xAxes: [{ 
              display: true 
            }], 
            yAxes: [{ 
              ticks: { 
                beginAtZero: true 
              } 
            }] 
          } 
        } 
 
      }); 
    } 
 
    function drawBarGraph(data, id) { 
      var labels = data.labels; 
      var chartLabel = data.chartLabel; 
      var chartdata = data.chartdata; 
      var ctx = document.getElementById(id).getContext('2d'); 
      var myChart = new Chart(ctx, { 
        type: 'bar', 
        data: { 
          labels: labels, 
          datasets: [{ 
            label: chartLabel, 
            data: chartdata, 
            backgroundColor: [ 
              'rgba(255, 99, 132, 0.2)', 
              'rgba(54, 162, 235, 0.2)', 
              'rgba(255, 206, 86, 0.2)', 
              'rgba(75, 192, 192, 0.2)', 
              'rgba(153, 102, 255, 0.2)', 
              'rgba(255, 159, 64, 0.2)' 
            ], 
            borderColor: [ 
              'rgba(255, 99, 132, 1)', 
              'rgba(54, 162, 235, 1)', 
              'rgba(255, 206, 86, 1)', 
              'rgba(75, 192, 192, 1)', 
              'rgba(153, 102, 255, 1)', 
              'rgba(255, 159, 64, 1)' 
            ], 
            borderWidth: 1 
          }] 
        }, 
        options: { 
          scales: { 
            yAxes: [{ 
              ticks: { 
                beginAtZero: true 
              } 
            }] 
          } 
        } 
      }); 
    }
</script>
{% endblock %}

templates/combine/index.html
{% extends "combine/base.html" %}
{% block body_block %}
<div style="text-align:center">
  <h1>
    Welcome to Combine App!
  </h1>
    <div class="container-fluid">
      <div class="container-fluid">
        <div class="row">
            <div class="col-3">
            <button onclick="click1()" >click me</button>
            </div>
            <div class="col-9">
            <span style="background-color:rgb(184, 172, 172)" id="customer"></span>
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getavg()">Get Average</button>
            </div>
            <div class="col-9" style="text-align:center">
            <input id="avg" type="text">
            <label>Result:</label>
            <span id="avg_res">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage()">load graph</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="500">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getPandas()">load table</button>
            </div>
            <div id="pandas" class="col-9">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getSBimage()">seaborn graph</button>
            </div>
            <div class="col-9">
                <img id="seaborn" width="1000">
            </div>
        <div>
    </div>
 
</div>
<script>
    function click1() {
        fetch('{% url "combine:get-num" %}')
            .then(res => res.text())
            .then(data => document.getElementById('customer').innerHTML = data)
    }
 
    function getavg() {
        var val_list = document.getElementById('avg').value;
		fetch('{% url "combine:get-avg" %}'+"?val="+val_list)
		.then(res => res.text())
		.then(data => document.getElementById('avg_res').innerHTML = data)
	}
 
// In our fetch request example(run fetch request live), we create a new request using the Request() constructor, 
//then use it to fetch a JPG.When the fetch is successful, we read a Blob out of the response using blob(), 
//put it into an object URL using URL.createObjectURL, and then set that URL as the source of 
//an < img > element to display the image.
 
    function getimage() {
		fetch('{% url "combine:get-graph" %}')
		.then(res => res.blob()) // we read a Blob out of the response using blob() #A binary large object (BLOB) is a collection of binary data stored as a single entity.
		.then(data => {
            let imgURL = URL.createObjectURL(data) //the URL lifetime is tied to the document in the window on which it was created
            document.getElementById('matplotlib').src = imgURL
        })
	}
 
    function getPandas() {
		fetch('{% url "combine:get-data" %}')
		.then(res => res.text())
		.then(data => document.getElementById('pandas').innerHTML = data)
	} 
 
    function getSBimage() {
		fetch('{% url "combine:get-seaborn-graph" %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('seaborn').src = imgURL
        })
	}
 
</script>
 
{% endblock %}

templates/combine/plotly.html
{% extends "combine/base.html" %}
{% block body_block%}
<div class="container-fluid">
    <center class="row">
        <h2>Our implementation of Plotly</h2>
    </center>
    <!--//The autoscape would be a protection against cross site scripting, not sql injection (which you need to make sure your inputs are scrubbed).-->
    {% autoescape off %}
    {{plot_div}}
    {% endautoescape %}
</div>
{% endblock %}

templates/combine/table.html
{% extends "combine/base.html" %}
{% block body_block%}
<div class="container-fluid">
    <center class="row">
        <h2>Our implementation of Django Tables</h2>
    </center>
    {% load django_tables2 %}
    {% render_table table %}
</div>
{% endblock %}